name = "movyz-akwam-queue-consumer"
main = "src/index.ts"
compatibility_date = "2026-10-04"

[[services]]
binding = "JOB_WORKER"
service = "movyz-akwam-job"

[[queues.consumers]]
queue = "movyz-akwam-fill"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "movyz-akwam-fill-dlq"
max_concurrency = 16
retry_delay = 60
workers_dev = false
