import type { CuratedCatalogItem } from './tmdb';

export const curatedCatalogSeed: CuratedCatalogItem[] = [
  { rank: 1, title: "Stranger Things", year: 2025, mediaType: "series" },
  { rank: 2, title: "Spider-Man: Brand New Day", year: 2026, mediaType: "movie" },
  { rank: 3, title: "The Odyssey", year: 2026, mediaType: "movie" },
  { rank: 4, title: "KPop Demon Hunters", year: 2025, mediaType: "movie" },
  { rank: 5, title: "Wednesday", year: 2025, mediaType: "series" },
  { rank: 6, title: "Squid Game", year: 2025, mediaType: "series" },
  { rank: 7, title: "Project Hail Mary", year: 2026, mediaType: "movie" },
  { rank: 8, title: "A Knight of the Seven Kingdoms", year: 2026, mediaType: "series" },
  { rank: 9, title: "One Piece", year: 2026, mediaType: "series" },
  { rank: 10, title: "Superman", year: 2025, mediaType: "movie" },
  { rank: 11, title: "Severance", year: 2025, mediaType: "series" },
  { rank: 12, title: "The Last of Us", year: 2025, mediaType: "series" },
  { rank: 13, title: "Toy Story 5", year: 2026, mediaType: "movie" },
  { rank: 14, title: "Frankenstein", year: 2025, mediaType: "movie" },
  { rank: 15, title: "Sinners", year: 2025, mediaType: "movie" },
  { rank: 16, title: "The Fantastic Four: First Steps", year: 2025, mediaType: "movie" },
  { rank: 17, title: "Michael", year: 2026, mediaType: "movie" },
  { rank: 18, title: "F1: The Movie", year: 2025, mediaType: "movie" },
  { rank: 19, title: "The White Lotus", year: 2025, mediaType: "series" },
  { rank: 20, title: "The Pitt", year: 2025, mediaType: "series" },
  { rank: 21, title: "Avatar: Fire and Ash", year: 2025, mediaType: "movie" },
  { rank: 22, title: "House of the Dragon", year: 2026, mediaType: "series" },
  { rank: 23, title: "The Super Mario Galaxy Movie", year: 2026, mediaType: "movie" },
  { rank: 24, title: "Daredevil: Born Again", year: 2025, mediaType: "series" },
  { rank: 25, title: "The Studio", year: 2025, mediaType: "series" },
  { rank: 26, title: "Zootopia 2", year: 2025, mediaType: "movie" },
  { rank: 27, title: "Wicked: For Good", year: 2025, mediaType: "movie" },
  { rank: 28, title: "The Devil Wears Prada 2", year: 2026, mediaType: "movie" },
  { rank: 29, title: "Jurassic World: Rebirth", year: 2025, mediaType: "movie" },
  { rank: 30, title: "The Bear", year: 2026, mediaType: "series" },
  { rank: 31, title: "How to Train Your Dragon", year: 2025, mediaType: "movie" },
  { rank: 32, title: "Dexter: Resurrection", year: 2025, mediaType: "series" },
  { rank: 33, title: "Mission: Impossible – The Final Reckoning", year: 2025, mediaType: "movie" },
  { rank: 34, title: "The Life List", year: 2025, mediaType: "movie" },
  { rank: 35, title: "The Old Guard 2", year: 2025, mediaType: "movie" },
  { rank: 36, title: "Pluribus", year: 2025, mediaType: "series" },
  { rank: 37, title: "The Mandalorian and Grogu", year: 2026, mediaType: "movie" },
  { rank: 38, title: "Alien: Earth", year: 2025, mediaType: "series" },
  { rank: 39, title: "Happy Gilmore 2", year: 2025, mediaType: "movie" },
  { rank: 40, title: "Black Mirror", year: 2025, mediaType: "series" },
  { rank: 41, title: "Scream 7", year: 2026, mediaType: "movie" },
  { rank: 42, title: "28 Years Later: The Bone Temple", year: 2026, mediaType: "movie" },
  { rank: 43, title: "The Gorge", year: 2025, mediaType: "movie" },
  { rank: 44, title: "Thunderbolts*", year: 2025, mediaType: "movie" },
  { rank: 45, title: "Captain America: Brave New World", year: 2025, mediaType: "movie" },
  { rank: 46, title: "The Amateur", year: 2025, mediaType: "movie" },
  { rank: 47, title: "The Accountant 2", year: 2025, mediaType: "movie" },
  { rank: 48, title: "Nobody Wants This", year: 2026, mediaType: "series" },
  { rank: 49, title: "Bridgerton", year: 2026, mediaType: "series" },
  { rank: 50, title: "The Woman in Cabin 10", year: 2025, mediaType: "movie" },
  { rank: 51, title: "A House of Dynamite", year: 2025, mediaType: "movie" },
  { rank: 52, title: "The Thursday Murder Club", year: 2025, mediaType: "movie" },
  { rank: 53, title: "The Great Flood", year: 2025, mediaType: "movie" },
  { rank: 54, title: "Straw", year: 2025, mediaType: "movie" },
  { rank: 55, title: "Havoc", year: 2025, mediaType: "movie" },
  { rank: 56, title: "The Last Frontier", year: 2025, mediaType: "series" },
  { rank: 57, title: "The Diplomat", year: 2026, mediaType: "series" },
  { rank: 58, title: "The Night Agent", year: 2026, mediaType: "series" },
  { rank: 59, title: "The Lincoln Lawyer", year: 2026, mediaType: "series" },
  { rank: 60, title: "Monster: The Lizzie Borden Story", year: 2026, mediaType: "series" },
  { rank: 61, title: "East of Eden", year: 2026, mediaType: "series" },
  { rank: 62, title: "Star City", year: 2026, mediaType: "series" },
  { rank: 63, title: "The Agency", year: 2026, mediaType: "series" },
  { rank: 64, title: "The Paper", year: 2026, mediaType: "series" },
  { rank: 65, title: "Nemesis", year: 2026, mediaType: "series" },
  { rank: 66, title: "His & Hers", year: 2026, mediaType: "series" },
  { rank: 67, title: "I Will Find You", year: 2026, mediaType: "series" },
  { rank: 68, title: "Run Away", year: 2026, mediaType: "series" },
  { rank: 69, title: "Man on Fire", year: 2026, mediaType: "series" },
  { rank: 70, title: "A Minecraft Movie", year: 2025, mediaType: "movie" },
  { rank: 71, title: "Lilo & Stitch", year: 2025, mediaType: "movie" },
  { rank: 72, title: "The Conjuring: Last Rites", year: 2025, mediaType: "movie" },
  { rank: 73, title: "Weapons", year: 2025, mediaType: "movie" },
  { rank: 74, title: "Until Dawn", year: 2025, mediaType: "movie" },
  { rank: 75, title: "Final Destination Bloodlines", year: 2025, mediaType: "movie" },
  { rank: 76, title: "Ballerina", year: 2025, mediaType: "movie" },
  { rank: 77, title: "Now You See Me: Now You Don’t", year: 2025, mediaType: "movie" },
  { rank: 78, title: "Predator: Badlands", year: 2025, mediaType: "movie" },
  { rank: 79, title: "Chainsaw Man – The Movie: Reze Arc", year: 2025, mediaType: "movie" },
  { rank: 80, title: "Demon Slayer: Infinity Castle", year: 2025, mediaType: "movie" },
  { rank: 81, title: "Mickey 17", year: 2025, mediaType: "movie" },
  { rank: 82, title: "Warfare", year: 2025, mediaType: "movie" },
  { rank: 83, title: "The Electric State", year: 2025, mediaType: "movie" },
  { rank: 84, title: "Exterritorial", year: 2025, mediaType: "movie" },
  { rank: 85, title: "Ad Vitam", year: 2025, mediaType: "movie" },
  { rank: 86, title: "My Oxford Year", year: 2025, mediaType: "movie" },
  { rank: 87, title: "Brick", year: 2025, mediaType: "movie" },
  { rank: 88, title: "Madea's Destination Wedding", year: 2025, mediaType: "movie" },
  { rank: 89, title: "The Wrong Paris", year: 2025, mediaType: "movie" },
  { rank: 90, title: "Counterattack", year: 2025, mediaType: "movie" },
  { rank: 91, title: "A Working Man", year: 2025, mediaType: "movie" },
  { rank: 92, title: "Novocaine", year: 2025, mediaType: "movie" },
  { rank: 93, title: "Companion", year: 2025, mediaType: "movie" },
  { rank: 94, title: "Heart Eyes", year: 2025, mediaType: "movie" },
  { rank: 95, title: "Drop", year: 2025, mediaType: "movie" },
  { rank: 96, title: "Wolf Man", year: 2025, mediaType: "movie" },
  { rank: 97, title: "Love Hurts", year: 2025, mediaType: "movie" },
  { rank: 98, title: "Presence", year: 2025, mediaType: "movie" },
  { rank: 99, title: "The End of Oak Street", year: 2026, mediaType: "movie" },
  { rank: 100, title: "Hoppers", year: 2026, mediaType: "movie" },
  { rank: 101, title: "Insidious: Out of the Further", year: 2026, mediaType: "movie" },
  { rank: 102, title: "Resident Evil", year: 2026, mediaType: "movie" },
  { rank: 103, title: "Mortal Kombat II", year: 2026, mediaType: "movie" },
  { rank: 104, title: "Supergirl", year: 2026, mediaType: "movie" },
  { rank: 105, title: "Wuthering Heights", year: 2026, mediaType: "movie" },
  { rank: 106, title: "Backrooms", year: 2026, mediaType: "movie" },
  { rank: 107, title: "Obsession", year: 2026, mediaType: "movie" },
  { rank: 108, title: "Disclosure Day", year: 2026, mediaType: "movie" },
  { rank: 109, title: "Practical Magic 2", year: 2026, mediaType: "movie" },
  { rank: 110, title: "Send Help", year: 2026, mediaType: "movie" },
  { rank: 111, title: "The Drama", year: 2026, mediaType: "movie" },
  { rank: 112, title: "The Invite", year: 2026, mediaType: "movie" },
  { rank: 113, title: "Crime 101", year: 2026, mediaType: "movie" },
  { rank: 114, title: "Verity", year: 2026, mediaType: "movie" },
  { rank: 115, title: "The Dog Stars", year: 2026, mediaType: "movie" },
  { rank: 116, title: "The Bride!", year: 2026, mediaType: "movie" },
  { rank: 117, title: "Mercy", year: 2026, mediaType: "movie" },
  { rank: 118, title: "The Mummy", year: 2026, mediaType: "movie" },
  { rank: 119, title: "Return to Silent Hill", year: 2026, mediaType: "movie" },
  { rank: 120, title: "Iron Lung", year: 2026, mediaType: "movie" },
  { rank: 121, title: "Mutiny", year: 2026, mediaType: "movie" },
  { rank: 122, title: "Heart of the Beast", year: 2026, mediaType: "movie" },
  { rank: 123, title: "The King’s Warden", year: 2026, mediaType: "movie" },
  { rank: 124, title: "Masters of the Universe", year: 2026, mediaType: "movie" },
  { rank: 125, title: "Scary Movie", year: 2026, mediaType: "movie" },
  { rank: 126, title: "GOAT", year: 2026, mediaType: "movie" },
  { rank: 127, title: "Coyote vs. Acme", year: 2026, mediaType: "movie" },
  { rank: 128, title: "The Chair Company", year: 2025, mediaType: "series" },
  { rank: 129, title: "Adolescence", year: 2025, mediaType: "series" },
  { rank: 130, title: "Andor", year: 2025, mediaType: "series" },
  { rank: 131, title: "Dept. Q", year: 2025, mediaType: "series" },
  { rank: 132, title: "Dying for Sex", year: 2025, mediaType: "series" },
  { rank: 133, title: "Task", year: 2025, mediaType: "series" },
  { rank: 134, title: "The Rehearsal", year: 2025, mediaType: "series" },
  { rank: 135, title: "Hacks", year: 2025, mediaType: "series" },
  { rank: 136, title: "The Righteous Gemstones", year: 2025, mediaType: "series" },
  { rank: 137, title: "Long Story Short", year: 2025, mediaType: "series" },
  { rank: 138, title: "The Buccaneers", year: 2025, mediaType: "series" },
  { rank: 139, title: "Slow Horses", year: 2025, mediaType: "series" },
  { rank: 140, title: "The Sandman", year: 2025, mediaType: "series" },
  { rank: 141, title: "Invincible", year: 2025, mediaType: "series" },
  { rank: 142, title: "Paradise", year: 2025, mediaType: "series" },
  { rank: 143, title: "When Life Gives You Tangerines", year: 2025, mediaType: "series" },
  { rank: 144, title: "The Trauma Code: Heroes on Call", year: 2025, mediaType: "series" },
  { rank: 145, title: "Weak Hero Class 2", year: 2025, mediaType: "series" },
  { rank: 146, title: "MobLand", year: 2025, mediaType: "series" },
  { rank: 147, title: "Your Friends & Neighbors", year: 2025, mediaType: "series" },
  { rank: 148, title: "The Pitt", year: 2026, mediaType: "series" },
  { rank: 149, title: "Crystal Lake", year: 2026, mediaType: "series" },
  { rank: 150, title: "Half Man", year: 2026, mediaType: "series" },
  { rank: 151, title: "Youth", year: 2026, mediaType: "series" },
  { rank: 152, title: "Rooster", year: 2026, mediaType: "series" },
  { rank: 153, title: "Ponies", year: 2026, mediaType: "series" },
  { rank: 154, title: "Maximum Pleasure Guaranteed", year: 2026, mediaType: "series" },
  { rank: 155, title: "Nocturne", year: 2026, mediaType: "series" },
  { rank: 156, title: "The Lowdown", year: 2026, mediaType: "series" },
  { rank: 157, title: "Beauty in Black", year: 2026, mediaType: "series" },
  { rank: 158, title: "The Gentlemen", year: 2026, mediaType: "series" },
  { rank: 159, title: "Outer Banks", year: 2026, mediaType: "series" },
  { rank: 160, title: "A Different World", year: 2026, mediaType: "series" },
  { rank: 161, title: "Not A Stranger", year: 2026, mediaType: "series" },
  { rank: 162, title: "Crew Girl", year: 2026, mediaType: "series" },
  { rank: 163, title: "Death of the Pastor’s Wife", year: 2026, mediaType: "series" },
  { rank: 164, title: "Agatha Christie’s Seven Dials", year: 2026, mediaType: "series" },
  { rank: 165, title: "Can This Love Be Translated?", year: 2026, mediaType: "series" },
  { rank: 166, title: "Unfamiliar", year: 2026, mediaType: "series" },
  { rank: 167, title: "Michael Jackson: The Verdict", year: 2026, mediaType: "series" },
  { rank: 168, title: "Teach You a Lesson", year: 2026, mediaType: "series" },
  { rank: 169, title: "Alice in Borderland", year: 2025, mediaType: "series" },
  { rank: 170, title: "Bloodhounds", year: 2025, mediaType: "series" },
  { rank: 171, title: "Monster", year: 2025, mediaType: "series" },
  { rank: 172, title: "Bon Appétit, Your Majesty", year: 2025, mediaType: "series" },
  { rank: 173, title: "The Paper", year: 2025, mediaType: "series" },
  { rank: 174, title: "Minions & Monsters", year: 2026, mediaType: "movie" },
  { rank: 175, title: "Pegasus 3", year: 2026, mediaType: "movie" },
  { rank: 176, title: "Blades of the Guardians", year: 2026, mediaType: "movie" },
  { rank: 177, title: "Detective Conan: Fallen Angel of the Highway", year: 2026, mediaType: "movie" },
  { rank: 178, title: "Kingdom 5", year: 2026, mediaType: "movie" },
  { rank: 179, title: "Scare Out", year: 2026, mediaType: "movie" },
  { rank: 180, title: "Dhurandhar: The Revenge", year: 2026, mediaType: "movie" },
  { rank: 181, title: "Kung Fu Soccer", year: 2026, mediaType: "movie" },
  { rank: 182, title: "Once Upon a Time in the Middle East", year: 2026, mediaType: "movie" },
  { rank: 183, title: "Chiikawa the Movie: The Secret of Mermaid Island", year: 2026, mediaType: "movie" },
  { rank: 184, title: "The White Lotus", year: 2025, mediaType: "series" },
  { rank: 185, title: "Squid Game", year: 2025, mediaType: "series" },
  { rank: 186, title: "Stranger Things", year: 2025, mediaType: "series" },
  { rank: 187, title: "The Eternaut", year: 2025, mediaType: "series" },
  { rank: 188, title: "Murderbot", year: 2025, mediaType: "series" },
  { rank: 189, title: "The Waterfront", year: 2025, mediaType: "series" },
  { rank: 190, title: "The Hunting Wives", year: 2025, mediaType: "series" },
  { rank: 191, title: "The Residence", year: 2025, mediaType: "series" },
  { rank: 192, title: "Zero Day", year: 2025, mediaType: "series" },
  { rank: 193, title: "Black Rabbit", year: 2025, mediaType: "series" },
  { rank: 194, title: "Sirens", year: 2025, mediaType: "series" },
  { rank: 195, title: "The Four Seasons", year: 2025, mediaType: "series" },
  { rank: 196, title: "The Naked Gun", year: 2025, mediaType: "movie" },
  { rank: 197, title: "The Running Man", year: 2025, mediaType: "movie" },
  { rank: 198, title: "The Pickup", year: 2025, mediaType: "movie" },
  { rank: 199, title: "Afterburn", year: 2025, mediaType: "movie" },
  { rank: 200, title: "The Summer I Turned Pretty", year: 2025, mediaType: "series" },
];